name: Generate a feed for my sites

on:
  push:
    branches: ["main"]

  schedule:
    - cron: '0 * * * *'

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      # build
      - uses: actions/checkout@main
      - name: Install Rust compiler
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - uses: erlef/setup-beam@main
        with:
          otp-version: '26.0.2'
          elixir-version: '1.15.5'
      - run: mix deps.get
      - name: Generate a feed
        run: mix run scripts/generate_feed.exs
      - name: Generate a JSON
        run: mix run scripts/generate_json.exs

      # deploy
      - name: Setup Pages
        uses: actions/configure-pages@main
      - name: Upload artifact
        uses: actions/upload-pages-artifact@main
        with:
          path: './output'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
